"""SX Bet venue adapters — FakeVenueAdapter and SXBetAdapter skeleton.

:class:`FakeVenueAdapter` is fully deterministic and offline-safe; it drives
all offline tests without any network calls.

:class:`SXBetAdapter` is a config-gated skeleton.  The SX Bet API is a
decentralised peer-to-peer exchange (SX Network, chainId 4162) whose order
submission requires EIP-712 wallet signatures generated by ``eth-account``.
Full live wiring is deferred until ``eth-account`` is confirmed as a project
dependency; live methods raise :exc:`NotImplementedError` behind the
``sx_bet_enabled`` config flag.

Research note (2026-06-28)
--------------------------
Authoritative SX Bet REST endpoints confirmed via Context7 (source:
``https://docs.sx.bet``):

- ``POST /orders`` — place a maker/taker order; requires EIP-712 signature.
- ``GET  /orders?maker=<address>`` — list open orders for a maker address.
- ``POST /orders/cancel/v2`` — cancel specific orders by hash (EIP-712 signed).
- ``POST /orders/cancel/all`` — cancel all open orders (EIP-712 signed).
- ``GET  /markets`` — fetch available markets.

Base URLs:
- Mainnet: ``https://api.sx.bet``
- Testnet: ``https://api.toronto.sx.bet`` (safe default; see ``sx_bet_base_url``)

Authentication uses EIP-712 wallet signatures (not a bearer token), so
credentials are ``sx_bet_maker_address`` and ``sx_bet_private_key``.

IMPORTANT: ``httpx`` is imported **lazily** inside async methods so that
``import veridex.venues.sx_bet`` is offline-safe and pulls no network library
at module load time (CON-010 async-shell / sync-core split).
"""

from __future__ import annotations

import time
import uuid
from typing import TYPE_CHECKING

from veridex.execution.models import ExecutionReceipt
from veridex.venues.base import (
    CancelAck,
    Order,
    OrderStatus,
    Quote,
    QuoteLevel,
    SubmitAck,
    build_receipt,
)

if TYPE_CHECKING:
    from veridex.config import Settings

# ---------------------------------------------------------------------------
# Fake native<->decimal conversion (explicit, documented)
# ---------------------------------------------------------------------------
#
# PRICE-UNIT DOCTRINE demo: the Fake keeps decimal odds (Veridex lingua franca) and a venue-native
# value strictly separate, with an EXPLICIT relationship so tests can prove no native value leaks
# into a decimal-odds field. The Fake's native unit is "implied probability in PERCENT" (a made-up
# but self-consistent stand-in for a real venue unit like SX implied odds or Polymarket
# probability): ``native = 100 / decimal`` and ``decimal = 100 / native``. A real adapter (T12-14,
# T17) substitutes its own venue formula here — the CONTRACT is only that ``Quote.price`` /
# ``OrderStatus.price`` stay decimal odds and ``native_price`` stays audit-only.
_FAKE_NATIVE_SCALE: float = 100.0


def _fake_decimal_to_native(decimal_odds: float) -> float:
    """Convert decimal odds to the Fake's native unit (implied probability, percent)."""
    return _FAKE_NATIVE_SCALE / decimal_odds


def _fake_native_to_decimal(native_price: float) -> float:
    """Convert the Fake's native unit (implied probability, percent) back to decimal odds."""
    return _FAKE_NATIVE_SCALE / native_price


# ---------------------------------------------------------------------------
# FakeVenueAdapter — deterministic, offline, no network
# ---------------------------------------------------------------------------


class FakeVenueAdapter:
    """Deterministic in-memory venue adapter for offline testing.

    All methods are async for interface symmetry with the live adapter but
    perform no I/O.  Behaviour is fully controlled by constructor flags so
    tests can exercise filled, partial-fill, and rejected paths without
    mocking or patching.

    Attributes:
        submit_calls: Counter incremented on each :meth:`submit_order` call;
            useful for asserting call counts in tests.
        status_calls: Counter incremented on each :meth:`get_order_status` call;
            lets poll tests assert exactly how many times the order was polled.
    """

    _FIXED_PRICE: float = 2.05  # decimal odds (Veridex lingua franca)
    _FIXED_SIZE: float = 500.0

    def __init__(
        self,
        *,
        fill: bool = True,
        fill_size: float | None = None,
        stay_pending: bool = False,
        pending_polls: int = 0,
    ) -> None:
        """Initialise the fake adapter.

        Args:
            fill: When ``True`` the adapter simulates an accepted fill (or
                partial fill when *fill_size* is less than the order size).
                When ``False`` all orders return a rejected status.
            fill_size: Optional override for the filled size returned by
                :meth:`get_order_status`.  When ``None``, a full fill is
                simulated (size equals the submitted order size).  Set to a
                value less than the order size to force a ``"partial"`` status.
            stay_pending: When ``True`` every :meth:`get_order_status` call
                returns a non-terminal ``"pending"`` status — drives the
                ``poll_order_terminal`` timeout path (honest UNRESOLVED, no
                fabricated fill).
            pending_polls: The first *N* :meth:`get_order_status` calls return
                ``"pending"`` before the terminal status is returned — drives
                the "flips to terminal on the Nth poll" path.
        """
        self._fill = fill
        self._fill_size = fill_size
        self._stay_pending = stay_pending
        self._pending_polls = pending_polls
        self._orders: dict[str, Order] = {}
        self.submit_calls: int = 0
        self.status_calls: int = 0

    async def quote_market(self, market_ref: str) -> Quote:
        """Return a fixed deterministic quote for any market reference.

        Args:
            market_ref: Venue-specific market identifier (ignored — fake
                always returns the same quote).

        Returns:
            A v2 :class:`~veridex.venues.base.Quote`: ``price`` is decimal odds,
            ``native_price`` is the venue-native value it derived from (audit only),
            and ``levels`` carry NATIVE book units.
        """
        native = _fake_decimal_to_native(self._FIXED_PRICE)
        return Quote(
            market_ref=market_ref,
            price=self._FIXED_PRICE,  # decimal odds
            native_price=native,  # audit only
            size=self._FIXED_SIZE,
            for_size=self._FIXED_SIZE,
            levels=[QuoteLevel(native_price=native, size=self._FIXED_SIZE)],
            ts=int(time.time()),
        )

    async def submit_order(self, order: Order) -> SubmitAck:
        """Record the order in memory and return an acceptance acknowledgement.

        Args:
            order: The order to simulate submitting.

        Returns:
            A :class:`~veridex.venues.base.SubmitAck` with a generated order ID.
        """
        venue_order_id = f"fake-{uuid.uuid4().hex[:8]}"
        self._orders[venue_order_id] = order
        self.submit_calls += 1
        return SubmitAck(venue_order_id=venue_order_id, accepted=self._fill)

    async def get_order_status(self, venue_order_id: str) -> OrderStatus:
        """Return a deterministic order status driven by constructor flags.

        The status string is chosen as follows:

        - ``stay_pending`` or within the first ``pending_polls`` calls → ``"pending"``
          (non-terminal; ``poll_order_terminal`` keeps polling / eventually times out)
        - ``fill=False``  → ``"rejected"``
        - ``fill=True`` and ``fill_size < order.size`` → ``"partial"``
        - ``fill=True`` and full fill → ``"filled"``

        The returned ``price`` is DECIMAL ODDS of the matched price; ``native_price`` carries
        the venue-native matched value for audit. A partial fill reports the MATCHED
        ``filled_size`` (``fill_size``), never the requested order size (SEC-004).

        Args:
            venue_order_id: The order reference to query.

        Returns:
            An :class:`~veridex.venues.base.OrderStatus` snapshot.
        """
        self.status_calls += 1
        native = _fake_decimal_to_native(self._FIXED_PRICE)

        # Transient non-terminal states: perpetual (timeout) or first N polls (flip-on-Nth).
        if self._stay_pending or self.status_calls <= self._pending_polls:
            return OrderStatus(
                venue_order_id=venue_order_id,
                status="pending",
                filled_size=0.0,
                price=self._FIXED_PRICE,
                native_price=native,
            )

        if not self._fill:
            return OrderStatus(
                venue_order_id=venue_order_id,
                status="rejected",
                filled_size=0.0,
                price=self._FIXED_PRICE,
                native_price=native,
            )

        order = self._orders.get(venue_order_id)
        requested_size = order.size if order else self._FIXED_SIZE

        if self._fill_size is not None and self._fill_size < requested_size:
            return OrderStatus(
                venue_order_id=venue_order_id,
                status="partial",
                filled_size=self._fill_size,  # MATCHED, not requested
                price=self._FIXED_PRICE,
                native_price=native,
            )

        return OrderStatus(
            venue_order_id=venue_order_id,
            status="filled",
            filled_size=requested_size,
            price=self._FIXED_PRICE,
            native_price=native,
        )

    async def cancel_order(self, venue_order_id: str) -> CancelAck:
        """Simulate a cancel — always succeeds.

        Args:
            venue_order_id: Order reference to cancel.

        Returns:
            :class:`~veridex.venues.base.CancelAck` with ``cancelled=True``.
        """
        self._orders.pop(venue_order_id, None)
        return CancelAck(venue_order_id=venue_order_id, cancelled=True)

    def normalize_receipt(
        self,
        execution_id: str,
        order: Order,
        status: OrderStatus,
        *,
        mode: str,
    ) -> ExecutionReceipt:
        """Convert a venue :class:`~veridex.venues.base.OrderStatus` into an
        :class:`~veridex.execution.models.ExecutionReceipt`.

        Delegates to :func:`~veridex.venues.base.build_receipt` — pure,
        synchronous, no credentials.

        Args:
            execution_id: Stable identifier shared with the parent
                :class:`~veridex.execution.models.ExecutionRecord`.
            order: The original order that was submitted.
            status: Current order status from the venue.
            mode: Execution mode label (``"dry_run"``, ``"paper"``,
                ``"live_guarded"``).

        Returns:
            An :class:`~veridex.execution.models.ExecutionReceipt` with no
            credentials attached.
        """
        return build_receipt(execution_id, order, status, mode=mode)


# ---------------------------------------------------------------------------
# SXBetAdapter — config-gated live skeleton
# ---------------------------------------------------------------------------


class SXBetAdapter:
    """Live SX Bet venue adapter — config-gated skeleton.

    The SX Bet API is a decentralised exchange (SX Network) using EIP-712
    wallet signatures for all order operations.  Full live wiring requires
    ``eth-account`` (not yet in project deps) and an active wallet.

    Live methods raise :exc:`NotImplementedError` until both:

    1. ``sx_bet_enabled = true`` is set in ``veridex/.env``.
    2. ``SX_BET_MAKER_ADDRESS`` and ``SX_BET_PRIVATE_KEY`` are configured.
    3. ``eth-account`` is added as a project dependency for EIP-712 signing.

    Constructor is dependency-free — :func:`~veridex.config.get_settings` is
    accessed only when a live method is called, keeping module import
    offline-safe (CON-010).

    ``httpx`` is imported **lazily** inside async methods — never at module
    level.
    """

    def __init__(self) -> None:
        """Initialise the adapter.

        No settings access here — credentials are resolved lazily inside
        the live methods to keep ``import veridex.venues.sx_bet`` offline-safe.
        """

    def _get_live_settings(self) -> tuple[Settings, str, str, str]:
        """Resolve and validate live settings; raise if the gate is not open.

        Returns:
            A ``(settings, base_url, maker_address, private_key)`` tuple.

        Raises:
            NotImplementedError: If ``sx_bet_enabled`` is ``False``.
            ValueError: If required credentials are missing.
        """
        from veridex.config import get_settings, require_sx_bet  # lazy config import

        settings = get_settings()
        if not settings.sx_bet_enabled:
            raise NotImplementedError("SX Bet live path pending: set SX_BET_ENABLED=true and provide credentials")
        maker_address, private_key = require_sx_bet(settings)
        return settings, settings.sx_bet_base_url, maker_address, private_key

    async def quote_market(self, market_ref: str) -> Quote:
        """Fetch a live price quote from SX Bet for *market_ref*.

        Calls ``GET /markets`` on the SX Bet REST API.

        Args:
            market_ref: Venue-specific market identifier.

        Returns:
            A :class:`~veridex.venues.base.Quote` snapshot.

        Raises:
            NotImplementedError: Live path not yet wired; see class docstring.
        """
        # TODO(P2B-3): lazy `import httpx`; map market_ref → SX Bet marketId,
        # call GET {base_url}/markets, parse response and return a real Quote.
        self._get_live_settings()
        raise NotImplementedError("SX Bet live path pending real API wiring: quote_market")

    async def submit_order(self, order: Order) -> SubmitAck:
        """Submit a bet order to SX Bet via EIP-712 signed ``POST /orders``.

        Args:
            order: The order to submit.

        Returns:
            A :class:`~veridex.venues.base.SubmitAck` from the venue.

        Raises:
            NotImplementedError: Live path not yet wired; see class docstring.
        """
        # TODO(P2B-3): lazy `import httpx`; construct EIP-712 signed order
        # payload (requires eth-account), call POST {base_url}/orders.
        self._get_live_settings()
        raise NotImplementedError("SX Bet live path pending real API wiring: submit_order")

    async def get_order_status(self, venue_order_id: str) -> OrderStatus:
        """Query the live status of an order on SX Bet.

        Calls ``GET /orders?maker=<address>`` and filters by *venue_order_id*.

        Args:
            venue_order_id: Opaque order hash returned by SX Bet.

        Returns:
            An :class:`~veridex.venues.base.OrderStatus` snapshot.

        Raises:
            NotImplementedError: Live path not yet wired; see class docstring.
        """
        # TODO(P2B-3): lazy `import httpx`; call
        # GET {base_url}/orders?maker={maker_address}, filter by venue_order_id.
        self._get_live_settings()
        raise NotImplementedError("SX Bet live path pending real API wiring: get_order_status")

    async def cancel_order(self, venue_order_id: str) -> CancelAck:
        """Cancel a specific SX Bet order via EIP-712 signed ``POST /orders/cancel/v2``.

        Args:
            venue_order_id: Order hash to cancel.

        Returns:
            A :class:`~veridex.venues.base.CancelAck`.

        Raises:
            NotImplementedError: Live path not yet wired; see class docstring.
        """
        # TODO(P2B-3): lazy `import httpx`; sign with CancelOrderV2SportX
        # EIP-712 domain, call POST {base_url}/orders/cancel/v2.
        self._get_live_settings()
        raise NotImplementedError("SX Bet live path pending real API wiring: cancel_order")

    def normalize_receipt(
        self,
        execution_id: str,
        order: Order,
        status: OrderStatus,
        *,
        mode: str,
    ) -> ExecutionReceipt:
        """Convert a venue :class:`~veridex.venues.base.OrderStatus` into an
        :class:`~veridex.execution.models.ExecutionReceipt`.

        Delegates to :func:`~veridex.venues.base.build_receipt` — pure,
        synchronous, no credentials.

        Args:
            execution_id: Stable identifier for the parent execution record.
            order: The original order submitted to the venue.
            status: Current order status from the venue.
            mode: Execution mode label.

        Returns:
            An :class:`~veridex.execution.models.ExecutionReceipt`.
        """
        return build_receipt(execution_id, order, status, mode=mode)
